# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'pyroscope', '= 0.5.12'
gem "sinatra", "~> 4.2", ">= 4.2.0"

gem "thin", "~> 2.0", ">= 2.0.0"
